version: "3.3"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    env_file:
      - ./conf/pro.env
    volumes:
      - .:/app
    command: >
      sh -c "uvicorn main:qms --host 0.0.0.0 --port 7777 --reload --forwarded-allow-ips '*'"
    ports:
      - "7777:7777"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge